import os

BOT_TOKEN = os.environ.get('BOT_TOKEN', '6814451088:AAFOLBu7M3dCI605Gol_bEccPYJNQwRcf7Q')
ADMIN = os.environ.get('ADMIN', 5934725286)
GROUP = os.environ.get('GROUP',1635762236)
AUTHORIZED_USER_IDS = [5934725286, 5377327708, 5817420325, 1918582402, 699882662, 1257545168, 1753264718, 1203220311, 6955248384, 752492336, 1673876488, 650599868, 1732613271, 1180727254, 1309190580, 967340481, 5322473767, 6426386490, 10368310407, 1036831407]
COMMANDS = ['/start', '/show', '/list', '/users', '/stats', '/test', '/neon']
SPECIAL = ['SEND_MESSAGE', 'SEND_FILE']
global last_update_id
last_update_id = -1
last_sent_time = None
VOICES = [
    ("https://raw.githubusercontent.com/guys-voice/voices/main/1.ogg", "V.V.Putin"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/2.ogg", "Kulib qoydim sanga, shavkat"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/3.ogg", "Kulib qoydim"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/4.ogg", "Nima bu"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/5.ogg", "Temola pilot 1"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/6.ogg", "Bir marta yozding indamadim"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/7.ogg", "Yot hammang, yot"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/8.ogg", "Gazni pulini bering"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/9.ogg", "Yaxsh"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/10.ogg", "Ya uka chichyording"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/11.ogg", "Hate emas, maqsad unique bo'lish"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/12.ogg", "Ollo rozi bo'sin"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/13.ogg", "Cringe"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/14.ogg", "Cringe 2"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/15.ogg", "Tupoy odam qomadi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/16.ogg", "Sohib"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/17.ogg", "Sohib king"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/18.ogg", "Sohib bot"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/19.ogg", "Qilig'ing yoqmaydi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/20.ogg", "Qarameng"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/21.ogg", "Ohio"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/22.ogg", "Na mehr qoldi na oqibat"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/23.ogg", "Murdoch university"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/24.ogg", "Maqsad yoq albatta"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/25.ogg", "O bu mano nima o'zi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/26.ogg", "Abdu kesang tiqamiz"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/27.ogg", "Katta tezlik bilan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/28.ogg", "Kim u"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/29.ogg", "Jiyaniim yopishtiraman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/30.ogg", "Oh no Jahongii"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/31.ogg", "Eshikni oching, gazdan keldik"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/32.ogg", "Man sani dadangmanmi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/33.ogg", "Yomurod dadam o'ldiradiku"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/34.ogg", "Chilparchin, uzr so'rayman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/35.ogg", "Yamon, tovushcha nima diyopti"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/36.ogg", "E bot bo'lopti Abdu"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/37.ogg", "Bir marta yozding indamadim"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/38.ogg", "Oh no cringe"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/39.ogg", "LOL 1"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/40.ogg", "Untitled"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/41.ogg", "Yemagan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/42.ogg", "Ko'rsa yitalaydi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/43.ogg", "LOL 2"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/44.ogg", "Nima bu nima"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/45.ogg", "Cringe 3"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/46.ogg", "17 secs of bullying Abdu"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/47.ogg", "Goher nasihatlari"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/48.ogg", "Cringe 4"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/49.ogg", "Bichara"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/50.ogg", "Abduni bitta gapi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/51.ogg", "Abdu 106"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/52.ogg", "Uxlamoqchiman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/53.ogg", "LOL 3"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/54.ogg", "LOL 4"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/55.ogg", "LOL 5"),
#   ("https://raw.githubusercontent.com/guys-voice/voices/main/56.ogg", "Shoxijon"), # BANNED BY AUTHOR
    ("https://raw.githubusercontent.com/guys-voice/voices/main/57.ogg", "Untitled"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/58.ogg", "Yaxshi, sohib sila"),
#   ("https://raw.githubusercontent.com/guys-voice/voices/main/59.ogg", "Massivni demanstratsiya qilaylik"), # BANNED BY AUTHOR
#   ("https://raw.githubusercontent.com/guys-voice/voices/main/60.ogg", "Yok"), # BANNED BY AUTHOR
#   ("https://raw.githubusercontent.com/guys-voice/voices/main/61.ogg", "Yolka"), # BANNED BY AUTHOR
#   ("https://raw.githubusercontent.com/guys-voice/voices/main/62.ogg", "Yaxshi, krisa"), # BANNED BY AUTHOR
    ("https://raw.githubusercontent.com/guys-voice/voices/main/63.ogg", "Mirkoff"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/64.ogg", "Untitled"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/65.ogg", "Kimdir yitiribti"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/66.ogg", "Untitled"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/67.ogg", "Mirko supuruvchi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/68.ogg", "Problem netu"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/69.ogg", "Ha"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/70.ogg", "Xo'sh 1"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/71.ogg", "Shoxa b*a"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/72.ogg", "Sui"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/73.ogg", "Yo murod, b*a"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/74.ogg", "Haaa 1"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/75.ogg", "Haaa 2"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/76.ogg", "Jahongir pakinul gruppe 1"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/77.ogg", "Murod sila"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/78.ogg", "Sabab yoq"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/79.ogg", "Jahongir pakinul gruppe 2"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/80.ogg", "Temola pilot 2"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/81.ogg", "Tezlash shoxa"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/82.ogg", "Ignor"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/83.ogg", "Wowo"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/84.ogg", "So'ra tualetga bo'sayam"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/85.ogg", "Yamon yegan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/86.ogg", "Vote qilamiz"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/87.ogg", "Yo murod, mirko"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/88.ogg", "Iye mirko"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/89.ogg", "Ha xo'sh"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/90.ogg", "Jiyan zvezdasan"),
#   ("https://raw.githubusercontent.com/guys-voice/voices/main/91.ogg", "Yemadi"), # DOES NOT WORK BY MISTAKE (I HAVE RUN THE PROGRAM BEFORE UPLOADING THE FILE)
    ("https://raw.githubusercontent.com/guys-voice/voices/main/92.ogg", "Bu hech nima bermaydi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/93.ogg", "Shavkat pakinul gruppe"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/94.ogg", "Yemadi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/95.ogg", "O sila"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/96.ogg", "Mirko qo'shiqchi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/97.ogg", "Makkilladizla"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/98.ogg", "Maqtov yorlig'i"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/99.ogg", "LOL 6"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/100.ogg", "Bachala tez, tez"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/101.ogg", "DNA, yomayo"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/102.ogg", "Boshqasi bormi, tasha"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/103.ogg", "Abduni sotaman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/104.ogg", "Ko'rganman buni, abdu"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/105.ogg", "Abdu tiqadi sani"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/106.ogg", "Raxmat, bilamiz"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/107.ogg", "Arqada o'tirib, oldindan olaymi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/108.ogg", "Qizlani arqasini olopti"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/109.ogg", "Yo murod"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/110.ogg", "S*koptimi jahon"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/111.ogg", "Shaxmat ko'ropti"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/112.ogg", "Qizig'i yoq, shukur"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/113.ogg", "Yoshda holi, yosh"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/114.ogg", "Shavkatni statistikasi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/115.ogg", "Abdu, o'zingdan ketma"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/116.ogg", "O' shuhrat"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/117.ogg", "Maqsad yoq, O'"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/118.ogg", "Mativatsion video ko'rdingmi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/119.ogg", "Unutamiz"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/120.ogg", "Bilmayman e"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/121.ogg", "Bo'lli raxmat e"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/122.ogg", "Jahon debatga nol"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/123.ogg", "N klassiko qachon"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/124.ogg", "Xo'sh 2"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/125.ogg", "Sabab yoq, baxti"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/126.ogg", "Toshkent sliv zonaku"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/127.ogg", "Nosni kayfi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/128.ogg", "Abdu, nachag'"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/129.ogg", "Xo'sh, variant beringla"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/130.ogg", "Abdu za*bat qilopti"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/131.ogg", "Nima bu, shoxa"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/132.ogg", "Mirko selfimi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/133.ogg", "Iy sohib jirkanch"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/134.ogg", "Gilos zo'r ekan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/135.ogg", "Muzika nima diyopti"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/136.ogg", "Shavkat qo'shiqchi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/137.ogg", "Jahon xeyter bo'ma 1"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/138.ogg", "Jahon xeyter bo'ma 2"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/139.ogg", "Don't interrupt me"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/140.ogg", "Shavkat admin ber"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/141.ogg", "Tezroq yoz jahon"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/142.ogg", "Bl*"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/143.ogg", "Sohibdir o'sha"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/144.ogg", "IQni ko'p ishlatmangla"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/145.ogg", "Qizig'i bor deb o'ylaydi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/146.ogg", "Mumkin emas dedila"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/147.ogg", "Qo'ling yopishganmi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/148.ogg", "Jahon qattasan ukam"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/149.ogg", "Maktab qachondan ekan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/150.ogg", "IQcha"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/151.ogg", "Aqllimisan mirko"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/152.ogg", "Man ijod qiganman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/153.ogg", "Chiqeveradi..."),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/154.ogg", "Hamma ko'rib bo'lli"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/155.ogg", "Akangni chempionligi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/156.ogg", "Shuhrat sila"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/157.ogg", "Qerasan baxti"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/158.ogg", "Avtobus kutib o'tirimman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/159.ogg", "Bordizlami"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/160.ogg", "Tax bo'llim boromman"),
    #("https://raw.githubusercontent.com/guys-voice/voices/main/161.ogg", "Kelinni aytmadi boxa"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/162.ogg", "Kelinni oti jahona"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/163.ogg", "Juda off bo'lli"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/164.ogg", "Umman off bo'mapti"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/165.ogg", "Oshib tushopti shoxa"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/166.ogg", "Jahon s..."),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/167.ogg", "Qizla choqiropti kelingla"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/168.ogg", "Shoxa off"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/169.ogg", "Tezlash boxa"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/170.ogg", "Sohib krinjoviy king"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/171.ogg", "Da*uya bo'lib ketadiku"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/172.ogg", "Turutu turutu"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/173.ogg", "Mirkoni kodi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/174.ogg", "Shukur sila"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/175.ogg", "Qisib o'tirish kerak edi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/176.ogg", "I wanna thank me"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/177.ogg", "LOL 7"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/178.ogg", "Maqsad munnan ko'rish"),
    #("https://raw.githubusercontent.com/guys-voice/voices/main/179.ogg", "Abdullo kayfullo"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/180.ogg", "Tushunningmi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/181.ogg", "Puling bo'sa kel"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/182.ogg", "O'tmishni unut"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/183.ogg", "Mirko sani o'diramiz"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/184.ogg", "Mirko krisada"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/185.ogg", "Mirkoga oqibat yoq"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/186.ogg", "Sherxan baxodirxon"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/187.ogg", "Nag'zmi shumo"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/188.ogg", "Mirko off topic"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/189.ogg", "Baxodir tushundizmi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/190.ogg", "Orqadan gapirma"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/191.ogg", "Uzur shukur"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/192.ogg", "Xich qerni bilmaysan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/193.ogg", "Sohib da*bayob"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/194.ogg", "Mirko sila"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/195.ogg", "Shukur murod bo'ma"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/196.ogg", "Tug'ilsang vinavat emasmanku"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/197.ogg", "Bir gap aytmayda"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/198.ogg", "Rost gapiromman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/199.ogg", "Xich kim bilmaydi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/200.ogg", "Yaxshi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/201.ogg", "Manimcha yoq"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/202.ogg", "Shavkat obviyuslashopsan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/203.ogg", "Beeline kirib yotibti"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/204.ogg", "Voiceni ignor qiladi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/205.ogg", "Qachon o'tiramiz"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/206.ogg", "Murodmisan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/207.ogg", "Ignormas ko'chagaman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/208.ogg", "Sanam bezor bo'llingmi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/209.ogg", "Videoni ko'rmapsanku"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/210.ogg", "Shercha bo'ganim yoq"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/211.ogg", "Jiyancham"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/212.ogg", "Nima diysan e"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/213.ogg", "Choq 50 ming"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/214.ogg", "Obro'ni to'kdi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/215.ogg", "Chi chi chi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/216.ogg", "Albatta"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/217.ogg", "Qanchaga oloding"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/218.ogg", "Tezlash komil"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/219.ogg", "Ahmad muhsin"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/220.ogg", "Nimalaga qodirsan shoxa"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/221.ogg", "Jiyanim sur"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/222.ogg", "Jahongir what's up"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/223.ogg", "Sadullo"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/224.ogg", "Sayib"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/225.ogg", "Nursulton"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/226.ogg", "Shohjahon"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/227.ogg", "Shoki shokat"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/228.ogg", "Bahodir"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/229.ogg", "Go play chess"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/230.ogg", "Abdullo"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/231.ogg", "Dindig' dindig'ovich"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/232.ogg", "Nasrat"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/233.ogg", "Obviyus edi go'zzuk"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/234.ogg", "Mirko sila"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/235.ogg", "Qiyomatli akam metroda"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/236.ogg", "Yoqat e"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/237.ogg", "Hammang hate qilishing kerak"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/238.ogg", "Agar linkni o'zgartirsam"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/239.ogg", "Reserch qisang yetadi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/240.ogg", "Mj"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/241.ogg", "Sadulloo"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/242.ogg", "Mirko chichiyording"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/243.ogg", "Skol*orum"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/244.ogg", "Davrani ko'tani chiqdiku"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/245.ogg", "Hd kachestvalik tashadim"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/246.ogg", "Bot salom bermaydiku"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/247.ogg", "Yaxshi 3"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/248.ogg", "Shaxsiyizga yubordim"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/249.ogg", "Kayf qilib yopishtirmaysanmi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/250.ogg", "Hamma takoyla yig'ilibtiku"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/251.ogg", "Qornim och edi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/252.ogg", "Boxaga o'xshaykon xonadoshim"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/253.ogg", "Qera va qerdan borasan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/254.ogg", "Mehriddin ustoz bo'lasan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/255.ogg", "Akang damage oladi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/256.ogg", "Videoni ko'rmamman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/257.ogg", "Prava bo'lishi kerak"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/258.ogg", "Silada prava oladi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/259.ogg", "Silani ukasidasan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/260.ogg", "Holi yoshsan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/261.ogg", "Maqsadim demage yetkazish"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/262.ogg", "Oliy maqsadimni aytmadim"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/263.ogg", "Yaxshi lekin tanimayman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/264.ogg", "Bir ikki oy gaplashadi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/265.ogg", "Yobanashakar nima bu"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/266.ogg", "Back to back steam and leaf"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/267.ogg", "Yaxshi 4"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/268.ogg", "Zahroni kanali"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/269.ogg", "Black and white"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/270.ogg", "Tezlash sani kutomman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/271.ogg", "Pisht"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/272.ogg", "Tojikmi shumo"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/273.ogg", "Yopishtirdim har doimgiday"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/274.ogg", "Tasvirlab ber"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/275.ogg", "Jiyanchasi bo'lasan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/276.ogg", "Manga raxmat de"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/277.ogg", "Bitta raxamt de bo'lli"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/278.ogg", "Maqsad bor deyopti"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/279.ogg", "Mirko s*kvottimi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/280.ogg", "Yoq yaqin 5 minut ichida"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/281.ogg", "Bir narsa deyolmayman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/282.ogg", "Vals uchun wuit boraymi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/283.ogg", "Yaxshiroq rezin ber"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/284.ogg", "Jonkala ko'p"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/285.ogg", "Valsga qeridan ushlaysan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/286.ogg", "Ko'ndirib bo'maykon jo'rang"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/287.ogg", "Yomg'ir quydi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/288.ogg", "Jahon krisa"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/289.ogg", "Unut qizlani"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/290.ogg", "Qizla bilan boy hayotim"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/291.ogg", "Yer jahonni nigohida"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/292.ogg", "Oval demman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/293.ogg", "Krinj video taxlaydi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/294.ogg", "Videosi chiqsa tashaysan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/295.ogg", "Zapal bo'lishini qerdan bilay"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/296.ogg", "Farqi bor lekin"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/297.ogg", "Toshkent shahri de"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/298.ogg", "Inglizchaga aytdim"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/299.ogg", "The best answer"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/300.ogg", "Detskiy rasm"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/301.ogg", "Uxlashi kelopti"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/302.ogg", "Ke xay to'shak qilaman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/303.ogg", "Dounla"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/304.ogg", "Go 1"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/305.ogg", "Chorsu taraflaga"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/306.ogg", "Tezroq kelishaylik"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/307.ogg", "Go metro bilan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/308.ogg", "Tovbamga tayandim"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/309.ogg", "Nechchi qoyasan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/310.ogg", "Maqsad miriqish"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/311.ogg", "Asosiysi bepul"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/312.ogg", "Miriqish"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/313.ogg", "Go 2"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/314.ogg", "Oliy maqsadingni aniqla"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/315.ogg", "Lyuboyingni yirtaman"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/316.ogg", "Uchib ke shuhrat"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/317.ogg", "Metro bormi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/318.ogg", "Maqsad metro"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/319.ogg", "Jahonni ko'ndiraylik"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/320.ogg", "Kelasanmi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/321.ogg", "Bot"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/322.ogg", "Metroga uchrashamiz"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/323.ogg", "Ke xay arazlama"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/324.ogg", "Ulani ustun ko'ropsanda"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/325.ogg", "Qera borasan ula bilan"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/326.ogg", "Magic city"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/327.ogg", "Morojni olsam kelasanmi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/328.ogg", "Rasmga tushmadingmi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/329.ogg", "Yengil 2 kilo"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/330.ogg", "Jumayevchi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/331.ogg", "Morjonachi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/332.ogg", "Qo'ling charchamaydimi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/333.ogg", "O'zbekiston s*kdi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/334.ogg", "Haqiqat g'olib chiqadi"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/335.ogg", "Nomer sotadigan bor"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/336.ogg", "Qiyomatli akam"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/337.ogg", "Oh no no"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/338.ogg", "J deb yuborganding"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/339.ogg", "Omadingni ber"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/340.ogg", "Fil"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/341.ogg", "Random eshakcha"),
    ("https://raw.githubusercontent.com/guys-voice/voices/main/342.ogg", "Ok")
]
